In [1]:
import numpy as np

np.array([[1, 2, 3],[4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
np.random.randint(50,100,size=(50, 5))

array([[59, 79, 96, 55, 90],
       [75, 61, 74, 86, 67],
       [97, 79, 79, 79, 98],
       [61, 85, 84, 52, 91],
       [57, 98, 83, 56, 74],
       [68, 73, 90, 98, 99],
       [63, 53, 68, 74, 78],
       [83, 58, 76, 64, 69],
       [76, 98, 67, 66, 87],
       [78, 94, 50, 68, 58],
       [51, 99, 92, 97, 86],
       [96, 59, 96, 83, 96],
       [57, 83, 57, 67, 89],
       [92, 69, 93, 81, 52],
       [84, 82, 81, 55, 82],
       [97, 85, 78, 75, 87],
       [92, 98, 74, 98, 89],
       [91, 86, 71, 69, 67],
       [94, 67, 59, 84, 50],
       [64, 65, 69, 82, 78],
       [69, 62, 79, 70, 52],
       [81, 78, 97, 86, 55],
       [63, 76, 71, 72, 67],
       [78, 83, 80, 72, 94],
       [91, 75, 56, 55, 94],
       [77, 96, 75, 84, 74],
       [81, 73, 92, 89, 55],
       [87, 60, 79, 55, 56],
       [64, 55, 61, 88, 90],
       [95, 95, 84, 92, 58],
       [90, 62, 65, 96, 70],
       [96, 91, 81, 86, 67],
       [82, 97, 75, 63, 98],
       [97, 89, 55, 77, 77],
       [50, 64

In [3]:
np.random.randint(50,100,size=(3, 50, 5))

array([[[77, 98, 82, 52, 86],
        [75, 60, 68, 50, 52],
        [77, 74, 88, 94, 71],
        [74, 60, 51, 80, 90],
        [84, 86, 85, 91, 97],
        [78, 55, 86, 59, 60],
        [82, 79, 62, 93, 95],
        [79, 74, 93, 95, 53],
        [74, 69, 77, 89, 63],
        [91, 70, 90, 76, 53],
        [95, 52, 66, 59, 63],
        [83, 97, 71, 78, 69],
        [94, 81, 83, 90, 86],
        [69, 65, 52, 70, 95],
        [71, 64, 79, 60, 86],
        [57, 92, 53, 50, 84],
        [66, 58, 51, 97, 96],
        [81, 60, 60, 97, 98],
        [52, 60, 70, 51, 63],
        [62, 68, 58, 55, 80],
        [96, 69, 73, 52, 60],
        [76, 70, 57, 68, 94],
        [89, 77, 71, 85, 81],
        [58, 90, 77, 86, 93],
        [90, 80, 94, 73, 67],
        [90, 62, 86, 80, 93],
        [83, 88, 54, 93, 89],
        [60, 62, 87, 54, 93],
        [57, 65, 97, 87, 77],
        [59, 89, 98, 85, 66],
        [83, 74, 58, 93, 69],
        [99, 86, 77, 57, 90],
        [70, 59, 70, 81, 96],
        [7

In [4]:
#查詢的property->shape,size,dtype,ndim

grade5 = np.random.randint(50,100,size=(3, 50, 5))
grade5.shape, grade5.size, grade5.ndim, grade5.dtype

((3, 50, 5), 750, 3, dtype('int64'))